// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxNcU_t55Nk9-Fdcwwj7oxTWLfu3kb9q0',
    appId: '1:505440963351:web:00197854a5ecedcc9f8552',
    messagingSenderId: '505440963351',
    projectId: 'handzy-c04d2',
    authDomain: 'handzy-c04d2.firebaseapp.com',
    storageBucket: 'handzy-c04d2.firebasestorage.app',
    measurementId: 'G-FPEE5SS7P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jj4ylL5eBcAEGyfjzuGudyFxOm-hCvA',
    appId: '1:505440963351:android:dee0ae28792a5b3f9f8552',
    messagingSenderId: '505440963351',
    projectId: 'handzy-c04d2',
    storageBucket: 'handzy-c04d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPq31ABp_loJ5fisSL0fUcF8cFK-sLmE',
    appId: '1:505440963351:ios:5b7ffdd78d78b2659f8552',
    messagingSenderId: '505440963351',
    projectId: 'handzy-c04d2',
    storageBucket: 'handzy-c04d2.firebasestorage.app',
    iosBundleId: 'com.example.handzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdPq31ABp_loJ5fisSL0fUcF8cFK-sLmE',
    appId: '1:505440963351:ios:5b7ffdd78d78b2659f8552',
    messagingSenderId: '505440963351',
    projectId: 'handzy-c04d2',
    storageBucket: 'handzy-c04d2.firebasestorage.app',
    iosBundleId: 'com.example.handzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxNcU_t55Nk9-Fdcwwj7oxTWLfu3kb9q0',
    appId: '1:505440963351:web:7d809addeaad53c69f8552',
    messagingSenderId: '505440963351',
    projectId: 'handzy-c04d2',
    authDomain: 'handzy-c04d2.firebaseapp.com',
    storageBucket: 'handzy-c04d2.firebasestorage.app',
    measurementId: 'G-GMB67VL081',
  );

}